server:
  port: 30040
  max-http-header-size: 184320
  servlet:
    context-path: /material
  tomcat:
    accesslog:
      enabled: true
      directory: /data/www/logs/material
      suffix: .log
      pattern: traceId=[%{traceId}i],rpcId=[%{rpcId}i],remote_addr=[%a],http_x_forward=[%{X-Forwarded-For}i],time=[%{yyyy-MM-dd HH:mm:ss SSS}t],request=[%r],status=[%s],byte=[%b],elapsed=[%T],refer=[%{Referer}i],ua=[%{User-Agent}i],x=[%X]
      prefix: tomcat-access_log
      maxDays: 15
management:
    endpoints:
      web:
        exposure:
            include: "*"
        base-path: /server/manage
    endpoint:
      health:
          enabled: true
          show-details: always
      shutdown:
          enabled: true
# http://127.0.0.1:8080/baseboot/server/manage/health
    health:
        redis:
            enabled: false
        rabbit:
            enabled: false
        db:
            enabled: false
        diskspace:
            path: .
spring:
    http:
        encoding.charset: UTF-8
        encoding.force: true
    jpa:
    # 更新数据表结构
      hibernate:
        ddl-auto: none
    # 在日志中打印出执行sql语句的信息
      show-sql: true
      properties:
          hibernate:
            format_sql: true
            jdbc:
                batch_size: 5000
                batch_versioned_data: true
            order_inserts: true
            order_updates: true
    application:
      name: material-service
    servlet:
      multipart:
        max-file-size: 3072MB
        max-request-size: 3072MB
    main:
      allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
ribbon:
  #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetries: 0
  #重试负载均衡其他的实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations : true
  ServerListRefreshInterval: 2000

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.izk.bigdata.domain.po