server:
  port: 8090
  max-http-header-size: 184320
  servlet:
    context-path: /
  tomcat:
    accesslog:
      enabled: true
      directory: /home/work/data/logs/tmser
      suffix: .log
      pattern: traceId=[%{traceId}i],rpcId=[%{rpcId}i],remote_addr=[%a],http_x_forward=[%{X-Forwarded-For}i],time=[%{yyyy-MM-dd HH:mm:ss SSS}t],request=[%r],status=[%s],byte=[%b],elapsed=[%T],refer=[%{Referer}i],ua=[%{User-Agent}i],x=[%X]
      prefix: tomcat-access_log
      maxDays: 15

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /server/manage
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  # http://127.0.0.1:8083/baseboot/server/manage/health
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false
    db:
      enabled: false
    diskspace:
      path: /data
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/tmser?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: YhsbjCfcys

config.sensitive.aes_key: qwertyuioplkjhgf
halo:
  download-timeout: 10m
  cache: memory
  workDir: /home/work/app/tmser/