server:
  port: 30040
  max-http-header-size: 184320
  servlet:
    context-path: /sample

nacos:
  config:
    enabled: true
    serverAddr: localhost:8848
    dataId: sample
    type: yaml
    autoRefresh: true
    bootstrap:
      logEnable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /server/manage
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  # http://127.0.0.1:8083/baseboot/server/manage/health
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false
    db:
      enabled: false
    diskspace:
      path: /data

spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: 123456

config.sensitive.aes_key: qwertyuioplkjhgf